
# Using the node alpine image to build the React app
image: node:alpine

variables:
  AWS_DEFAULT_REGION: eu-central-1 # The region of our S3 bucket
  BUCKET_NAME: thedjhub.io         # Your bucket name


  PUBLIC_URL: /thedjhub
# Cache node modules - speeds up future builds
cache:
  paths:
    - node_modules
    - vendor

# Name the stages involved in the pipeline
stages:
  - test
  - build

# Job name for gitlab to recognise this results in assets for Gitlab Pages
# https://docs.gitlab.com/ee/user/project/pages/introduction.html#gitlab-pages-requirements

build:
  stage: build
  script:
  - npm install # Install all dependencies
  - npm run build --prod # Build for prod
  - cp public/index.html public/404.html # Not necessary, but helps with https://medium.com/@pshrmn/demystifying-single-page-applications-3068d0555d46

test:
  stage: test
  script:
    - npm install # Install all dependencies
